import json

file_path = 'd:/Kuliah/Skripsi/scrap_skripsi.ipynb'
with open(file_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

code = [
    "import os\n",
    "import io\n",
    "import requests\n",
    "import pytesseract\n",
    "from PIL import Image\n",
    "from PyPDF2 import PdfWriter, PdfReader\n",
    "import urllib3\n",
    "urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)\n",
    "\n",
    "def download_and_ocr_to_pdf(base_url, total_images, output_folder, pdf_filename):\n",
    "    pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'\n",
    "    if not os.path.exists(output_folder):\n",
    "        os.makedirs(output_folder)\n",
    "    \n",
    "    print(f\"Mengecek gambar di folder '{output_folder}' dan mendownload sisa halaman...\")\n",
    "    \n",
    "    downloaded_files = []\n",
    "    i = 1\n",
    "    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}\n",
    "    \n",
    "    while True:\n",
    "        file_name = f\"{i}.jpg\"\n",
    "        file_path = os.path.join(output_folder, file_name)\n",
    "        \n",
    "        if os.path.exists(file_path):\n",
    "            downloaded_files.append(file_path)\n",
    "        else:\n",
    "            image_url = f\"{base_url}{i}.jpg\"\n",
    "            try:\n",
    "                response = requests.get(image_url, headers=headers, verify=False, timeout=30)\n",
    "                if response.status_code == 404:\n",
    "                    print(f\"Halaman {i} tidak ditemukan. Berhenti mendownload.\")\n",
    "                    break\n",
    "                response.raise_for_status()\n",
    "                with open(file_path, 'wb') as f:\n",
    "                    f.write(response.content)\n",
    "                print(f\"Berhasil mengunduh: {file_name}\")\n",
    "                downloaded_files.append(file_path)\n",
    "            except Exception as e:\n",
    "                print(f\"Selesai atau error di {file_name}: {e}\")\n",
    "                break\n",
    "        i += 1\n",
    "        # Limit safety check\n",
    "        if i > 500: break\n",
    "\n",
    "    if not downloaded_files:\n",
    "        print(\"Tidak ada gambar.\")\n",
    "        return\n",
    "    \n",
    "    print(f\"\\nMemulai proses OCR untuk {len(downloaded_files)} halaman...\")\n",
    "    downloaded_files.sort(key=lambda f: int(os.path.basename(f).split('.')[0]))\n",
    "    \n",
    "    output_pdf = PdfWriter()\n",
    "    stream_refs = [] # FIX MEMORY BUG\n",
    "    \n",
    "    for filename in downloaded_files:\n",
    "        print(f\"Memproses: {os.path.basename(filename)}\")\n",
    "        try:\n",
    "            # Gunakan metode original agar glyph box rapi & HD\n",
    "            pdf_bytes = pytesseract.image_to_pdf_or_hocr(filename, extension='pdf', lang='ind')\n",
    "            pdf_stream = io.BytesIO(pdf_bytes)\n",
    "            stream_refs.append(pdf_stream)\n",
    "            reader = PdfReader(pdf_stream)\n",
    "            output_pdf.add_page(reader.pages[0])\n",
    "        except Exception as e:\n",
    "            print(f\"Error {filename}: {e}\")\n",
    "            \n",
    "    with open(pdf_filename, \"wb\") as f:\n",
    "        output_pdf.write(f)\n",
    "    print(f\"\\nSelesai! PDF tersimpan di: {pdf_filename}\")\n",
    "\n",
    "BASE_URL = \"https://ir.unair.ac.id/uploaded_files/temporary/DigitalCollection/NmM0YjE4NzU4YWYxNWM3NTEwMGI2MTQ0YjAxNTk5MjQ5YmY3NTQ1Nw==/files/mobile/\"\n",
    "OUTPUT_FOLDER = \"Judul Skripsi Kating\"\n",
    "PDF_OUTPUT_FILENAME = \"Judul Skripsi Kating_HD_Urut.pdf\"\n",
    "\n",
    "download_and_ocr_to_pdf(BASE_URL, 0, OUTPUT_FOLDER, PDF_OUTPUT_FILENAME)\n"
]

nb['cells'][1]['source'] = code
with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
print("Updated Notebook Successfully")
