import json

file_path = 'd:/Kuliah/Skripsi/scrap_skripsi.ipynb'
with open(file_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

code = [
    "import os\n",
    "import io\n",
    "import requests\n",
    "import pytesseract\n",
    "from PIL import Image\n",
    "from PyPDF2 import PdfWriter, PdfReader\n",
    "import urllib3\n",
    "urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)\n",
    "\n",
    "def download_and_ocr_to_pdf(base_url, output_folder, pdf_filename):\n",
    "    pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'\n",
    "    if not os.path.exists(output_folder):\n",
    "        os.makedirs(output_folder)\n",
    "    \n",
    "    print(f\"--- TAHAP 1: DOWNLOAD GAMBAR ---\")\n",
    "    i = 1\n",
    "    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}\n",
    "    \n",
    "    # Kita terus download sampai dapat 404\n",
    "    while True:\n",
    "        file_name = f\"{i}.jpg\"\n",
    "        file_path = os.path.join(output_folder, file_name)\n",
    "        \n",
    "        if os.path.exists(file_path):\n",
    "            # Opsional: Bisa tambahkan verifikasi file size di sini jika perlu\n",
    "            pass\n",
    "        else:\n",
    "            image_url = f\"{base_url}{i}.jpg\"\n",
    "            try:\n",
    "                response = requests.get(image_url, headers=headers, verify=False, timeout=30)\n",
    "                if response.status_code == 404:\n",
    "                    print(f\"Halaman {i} tidak ditemukan (Akhir dokumen). Berhenti mendownload.\")\n",
    "                    break\n",
    "                response.raise_for_status()\n",
    "                with open(file_path, 'wb') as f:\n",
    "                    f.write(response.content)\n",
    "                print(f\"Berhasil mengunduh: {file_name}\")\n",
    "            except Exception as e:\n",
    "                print(f\"Error di halaman {i}: {e}\")\n",
    "                break\n",
    "        i += 1\n",
    "        if i > 500: break # Safety limit\n",
    "\n",
    "    print(f\"\\n--- TAHAP 2: PROSES PDF & OCR ---\")\n",
    "    \n",
    "    # Ambil semua file .jpg di folder\n",
    "    all_files = [f for f in os.listdir(output_folder) if f.endswith('.jpg')]\n",
    "    \n",
    "    # LOGIKA PENTING: Urutkan berdasarkan angka murni\n",
    "    # Tanpa ini, urutannya jadi: 1.jpg, 10.jpg, 100.jpg, 11.jpg, dst.\n",
    "    all_files.sort(key=lambda x: int(os.path.basename(x).split('.')[0]))\n",
    "    \n",
    "    print(f\"Ditemukan {len(all_files)} gambar. Menyusun secara urut...\")\n",
    "    \n",
    "    output_pdf = PdfWriter()\n",
    "    stream_refs = [] # Untuk menjaga memory agar tidak corrupt\n",
    "    \n",
    "    for file_name in all_files:\n",
    "        file_path = os.path.join(output_folder, file_name)\n",
    "        print(f\"Menambahkan ke PDF: {file_name}\")\n",
    "        \n",
    "        try:\n",
    "            # 1. OCR ke PDF bytes\n",
    "            # Lang 'ind' untuk Bahasa Indonesia agar teks presisi\n",
    "            pdf_bytes = pytesseract.image_to_pdf_or_hocr(file_path, extension='pdf', lang='ind')\n",
    "            \n",
    "            # 2. Masukkan ke stream memory\n",
    "            pdf_stream = io.BytesIO(pdf_bytes)\n",
    "            stream_refs.append(pdf_stream) # WAJIB: Agar tidak hilang saat loop lanjut\n",
    "            \n",
    "            # 3. Baca stream dan tambahkan ke PDF utama\n",
    "            reader = PdfReader(pdf_stream)\n",
    "            output_pdf.add_page(reader.pages[0])\n",
    "            \n",
    "        except Exception as e:\n",
    "            print(f\"GAGAL memproses {file_name}: {e}\")\n",
    "            \n",
    "    # Pastikan file tidak sedang dibuka sebelum menulis\n",
    "    try:\n",
    "        with open(pdf_filename, \"wb\") as f:\n",
    "            output_pdf.write(f)\n",
    "        print(f\"\\nSUKSES! PDF tersimpan sebagai: {pdf_filename}\")\n",
    "    except PermissionError:\n",
    "        print(f\"\\nERROR: Tidak bisa menyimpan file. Pastikan '{pdf_filename}' sedang TIDAK DIBUKA di aplikasi lain.\")\n",
    "\n",
    "# CONFIG\n",
    "BASE_URL = \"https://ir.unair.ac.id/uploaded_files/temporary/DigitalCollection/NmM0YjE4NzU4YWYxNWM3NTEwMGI2MTQ0YjAxNTk5MjQ5YmY3NTQ1Nw==/files/mobile/\"\n",
    "FOLDER_NAMA = \"Judul Skripsi Kating\"\n",
    "OUTPUT_PDF = \"Judul_Skripsi_Fix_Urut.pdf\"\n",
    "\n",
    "download_and_ocr_to_pdf(BASE_URL, FOLDER_NAMA, OUTPUT_PDF)\n"
]

nb['cells'][1]['source'] = code
with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
print("Updated Notebook with Fixed Ordering Logic")
